### ISSUE TITLE
Value does not have datatype error with sh:datatype xsd:anyURI

### ISSUE THREAD

**Issue by Abrom8** [zazuko/rdf-validate-shacl#103]
Properties with `sh:datatype xsd:anyURI` always produce `Value does not have datatype <http://www.w3.org/2001/XMLSchema#anyURI>` error.

I created a minimal example for the https://shacl-playground.zazuko.com/ playground.

Shapes Graph:
```
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix g-validation:  <http://localhost:3001/shapes/validation#> .

@prefix g-framework: <http://localhost:3001/shapes/g-framework#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

g-validation:ServiceShape
	a sh:NodeShape ;
	sh:targetClass g-framework:Service ;
	sh:property [ sh:path g-framework:content ;
	                       sh:datatype xsd:anyURI ] ;
.
```

Data Graph:
```
{
    "@context": {
        "g-framework": "http://localhost:3001/shapes/g-framework#",
        "g-validation": "http://localhost:3001/shapes/validation#",
        "sh": "http://www.w3.org/ns/shacl#",
        "xsd": "http://www.w3.org/2001/XMLSchema#"
    },
  "@type": "g-framework:Service",
  "g-framework:content": "http://example.org/"
  
}
```

**Comment by tpluscode** [comment]
Thank you for reporting.

In your case, the error is in fact correct because the value is a [plain literal](https://s.zazuko.com/3nhigUw). The validation `sh:datatype` is strict in that it requires a literal to have an exact matching datatype. Compare with [other SHACL implementations](https://rdfshape.weso.es/shaclValidate?data=%40prefix%20sh%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%40prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20.%0A%40prefix%20g-framework%3A%20%3Chttp%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fg-framework%23%3E%20.%0A%40prefix%20g-validation%3A%20%3Chttp%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fvalidation%23%3E%20.%0A%0A_%3Ab0%20a%20g-framework%3AService%20%3B%0A%09g-framework%3Acontent%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.&dataFormat=turtle&dataInference=NONE&dataSource=byText&schema=%40prefix%20sh%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20g-validation%3A%20%20%3Chttp%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fvalidation%23%3E%20.%0A%0A%40prefix%20g-framework%3A%20%3Chttp%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fg-framework%23%3E%20.%0A%40prefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%0Ag-validation%3AServiceShape%0A%09a%20sh%3ANodeShape%20%3B%0A%09sh%3AtargetClass%20g-framework%3AService%20%3B%0A%09sh%3Aproperty%20%5B%20sh%3Apath%20g-framework%3Acontent%20%3B%0A%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3Adatatype%20xsd%3AanyURI%20%5D%20%3B%0A.&schemaEngine=JenaSHACL&schemaFormat=turtle&schemaInference=NONE&schemaSource=byText&triggerMode=TargetDecls), all of which yield same result.

If you need your JSON-LD to keep its idiomatic form, you can modify the `@context` to have it [assert the values of the `content` property](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22g-framework%22%3A%22http%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fg-framework%23%22%2C%22g-validation%22%3A%22http%3A%2F%2Flocalhost%3A3001%2Fshapes%2Fvalidation%23%22%2C%22sh%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22g-framework%3Acontent%22%3A%7B%22%40type%22%3A%22xsd%3AanyURI%22%7D%7D%2C%22%40type%22%3A%22g-framework%3AService%22%2C%22g-framework%3Acontent%22%3A%22http%3A%2F%2Fexample.org%2F%22%7D):

```diff
{
  "@context": {
    "g-framework": "http://localhost:3001/shapes/g-framework#",
    "g-validation": "http://localhost:3001/shapes/validation#",
    "sh": "http://www.w3.org/ns/shacl#",
-   "xsd": "http://www.w3.org/2001/XMLSchema#"
+   "xsd": "http://www.w3.org/2001/XMLSchema#",
+   "g-framework:content": {
+     "@type": "xsd:anyURI"
+   }
  },
  "@type": "g-framework:Service",
  "g-framework:content": "http://example.org/"
}
```

**Comment by tpluscode** [comment]
On a related note, the actual URI is not actually validated for correctness. One might argue that it should (we do that for numeric values and dates) but none of the other implementations available on https://rdfshape.weso.es/shaclValidate do that either...

**Comment by Abrom8** [comment]
Thank you! The example with the `@context` helped a lot! 👏
