### ISSUE TITLE
Validation result does not include a sh:resultMessage (and sometimes sh:value)

### ISSUE THREAD

**Issue by bmark92** [zazuko/rdf-validate-shacl#47]
We encountered two small bugs: 
1) the validation result does not include a sh:resultMessage when a ClassConstraintComponent is violated.

2) In some cases, the validation result also does not include a sh:value for violations of ClassConstraintComponent. (Some validation results do emit sh:value; maybe this only works for literals ATM)

We made a minimal working example of the issues. To make it work, download the zip file, and use the following in the Linux terminal:
```
cd MWE # (given the location where it was extracted)
node script.js
```

The two most important files in the working example are data.ttl and shapes.ttl.

[MWE.zip](https://github.com/zazuko/rdf-validate-shacl/files/5763731/MWE.zip)

**Comment by martinmaillard** [comment]
I would not qualify these as bugs since `sh:resultMessage` and `sh:value` are optional in the spec.

Some of the constraints currently don't have a default validation message, we inherited that from the original implementation. But if we find a good generic message for them, we can totally add it. Suggestions welcome :)
